### ISSUE TITLE
additive vibration Harm controls do nothing

### ISSUE THREAD

**Issue by glocke01** [TimeControlledOrganism/LifeFormModular#1]
Rack 1.1.5 running on 64 bit Ubuntu 18.04.3 LTS.

The Harm1/2/3 sliders have no effect that I can discern.

**Comment by TimeControlledOrganism** [comment]
Thx 
have you set the FM level to something other than 0 ?
the harm sliders are volume controls for the harmonics to modulate the carrier oscillator
you have to set fm to the depth you want (move the fm lvl knob to something othen than zero) and then feed the vca with the harmonics you want (adjust the harm sliders)

**Comment by glocke01** [comment]
Gotcha. My mistake!
